### PR TITLE
fix: made Data Table into MUI.

### LINKED ISSUE #74: Number of rows in preview should be restricted when creating a new analysis
The number of rows in a config file has the potential to be very large. Having the full table displayed interrupts the 1-2-3 flow as the user has to scroll down to find the `Initialise KinFin analysis` button. Initial config preview should be limited to ~10 rows with an option to show all. For very large config files we may need to introduce pagination.

### PR DESCRIPTION
**Pull request by heisdinesh**
- AT any time only 7 rows are shown, and rest can be seen on scroll
- At any time user can see 3 stpes of define-node-labels.
- Closes #74 
image

## Summary by Sourcery

Migrate the custom DataTable component to use MUI Table components with a fixed height scrollable container and sticky headers, and apply related style updates across DataTable, FileUpload, and DefineNodeLabels views.

Enhancements:
- Replace the HTML table in DataTable with MUI Table, TableContainer, Paper, and Typography components
- Limit DataTable display height and enable vertical scrolling with a sticky header
- Use MUI Typography for empty and invalid data messages
- Remove custom table SCSS in favor of MUI styling, retaining only error highlight styles
- Add margin reset to FileUpload h4 elements
- Reduce padding on DefineNodeLabels workflow steps to adjust visible content

### CODE REVIEW

**Comment by heisdinesh** [comment]
@rjchallis you can review this.

File: src/ui/src/components/FileUpload/DataTable/index.jsx [hunk 1]
```diff
@@ -1,95 +1,116 @@
...
+
+                return (
+                  <TableCell
+                    key={head}
+                    className={cellError ? styles.invalidCell : ""}
+                    title={cellError || ""}
+                    {...(allowEdit && {
+                      contentEditable: true,
+                      suppressContentEditableWarning: true,
+                      onBlur: (e) => handleCellEdit(e, idx, head),
```
Comment (rjchallis) [inline src/ui/src/components/FileUpload/DataTable/index.jsx:102]: Include an onKeyPress here to trigger blur on Enter as for the header

**Review by rjchallis — CHANGES_REQUESTED** [review]
Looks good. This is working well so think mixing contentEditable with MUI TableCell is fine for this use case. 

Only minor change request is to add an onKeyPress handler so the table body cells update on Enter to match the header behaviour
